
namespace SOFTWARE_INVENTARIO
{
    partial class FormPersonas
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormPersonas));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.dataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.groupBox1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txt_codper = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.button8 = new System.Windows.Forms.Button();
            this.PBox1 = new Guna.UI.WinForms.GunaCirclePictureBox();
            this.cbx_Cargo = new Guna.UI2.WinForms.Guna2ComboBox();
            this.txt_Correo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Telefono = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Direccion = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Btn_Actualizar = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Eliminar = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Guardar = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Nuevo = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Salir = new Guna.UI2.WinForms.Guna2Button();
            this.txt_Apellido = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Nombre = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Codigo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Txt_Buscar = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Ant = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Sig = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Pri = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Ult = new Guna.UI.WinForms.GunaAdvenceButton();
            this.guna2Elipse1 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2Elipse2 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2ShadowForm1 = new Guna.UI2.WinForms.Guna2ShadowForm(this.components);
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this.dataGridView1.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.dataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Sunken;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridView1.ColumnHeadersHeight = 40;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(188)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.Name = null;
            this.dataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(188)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(188)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridView1.EnableHeadersVisualStyles = false;
            this.dataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.dataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridView1.Location = new System.Drawing.Point(6, 12);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            this.dataGridView1.RowHeadersVisible = false;
            this.dataGridView1.RowTemplate.Height = 40;
            this.dataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridView1.Size = new System.Drawing.Size(925, 626);
            this.dataGridView1.TabIndex = 2;
            this.dataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DodgerBlue;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.groupBox1);
            this.bunifuGroupBox1.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(943, 0);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(323, 700);
            this.bunifuGroupBox1.TabIndex = 3;
            this.bunifuGroupBox1.TabStop = false;
            // 
            // groupBox1
            // 
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.groupBox1.BorderRadius = 8;
            this.groupBox1.BorderThickness = 1;
            this.groupBox1.Controls.Add(this.txt_codper);
            this.groupBox1.Controls.Add(this.button8);
            this.groupBox1.Controls.Add(this.PBox1);
            this.groupBox1.Controls.Add(this.cbx_Cargo);
            this.groupBox1.Controls.Add(this.txt_Correo);
            this.groupBox1.Controls.Add(this.txt_Telefono);
            this.groupBox1.Controls.Add(this.txt_Direccion);
            this.groupBox1.Controls.Add(this.Btn_Actualizar);
            this.groupBox1.Controls.Add(this.Btn_Eliminar);
            this.groupBox1.Controls.Add(this.Btn_Guardar);
            this.groupBox1.Controls.Add(this.Btn_Nuevo);
            this.groupBox1.Controls.Add(this.Btn_Salir);
            this.groupBox1.Controls.Add(this.txt_Apellido);
            this.groupBox1.Controls.Add(this.txt_Nombre);
            this.groupBox1.Controls.Add(this.txt_Codigo);
            this.groupBox1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.groupBox1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.groupBox1.Location = new System.Drawing.Point(6, 13);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.PanelColor = System.Drawing.Color.White;
            this.groupBox1.PanelColor2 = System.Drawing.Color.White;
            this.groupBox1.ShadowColor = System.Drawing.Color.DarkGray;
            this.groupBox1.ShadowDept = 2;
            this.groupBox1.ShadowDepth = 2;
            this.groupBox1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.groupBox1.ShadowTopLeftVisible = false;
            this.groupBox1.Size = new System.Drawing.Size(311, 681);
            this.groupBox1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.groupBox1.TabIndex = 0;
            // 
            // txt_codper
            // 
            this.txt_codper.AcceptsReturn = false;
            this.txt_codper.AcceptsTab = false;
            this.txt_codper.AnimationSpeed = 200;
            this.txt_codper.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_codper.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_codper.BackColor = System.Drawing.Color.Transparent;
            this.txt_codper.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_codper.BackgroundImage")));
            this.txt_codper.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            this.txt_codper.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_codper.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            this.txt_codper.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_codper.BorderRadius = 8;
            this.txt_codper.BorderThickness = 2;
            this.txt_codper.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_codper.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_codper.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_codper.DefaultText = "";
            this.txt_codper.FillColor = System.Drawing.Color.White;
            this.txt_codper.ForeColor = System.Drawing.Color.Gray;
            this.txt_codper.HideSelection = true;
            this.txt_codper.IconLeft = null;
            this.txt_codper.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_codper.IconPadding = 10;
            this.txt_codper.IconRight = null;
            this.txt_codper.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_codper.Lines = new string[0];
            this.txt_codper.Location = new System.Drawing.Point(16, 377);
            this.txt_codper.MaxLength = 32767;
            this.txt_codper.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_codper.Modified = false;
            this.txt_codper.Multiline = false;
            this.txt_codper.Name = "txt_codper";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_codper.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_codper.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_codper.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Gray;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_codper.OnIdleState = stateProperties4;
            this.txt_codper.PasswordChar = '\0';
            this.txt_codper.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_codper.PlaceholderText = "Codigo | Persona";
            this.txt_codper.ReadOnly = false;
            this.txt_codper.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_codper.SelectedText = "";
            this.txt_codper.SelectionLength = 0;
            this.txt_codper.SelectionStart = 0;
            this.txt_codper.ShortcutsEnabled = true;
            this.txt_codper.Size = new System.Drawing.Size(279, 38);
            this.txt_codper.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_codper.TabIndex = 135;
            this.txt_codper.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_codper.TextMarginBottom = 0;
            this.txt_codper.TextMarginLeft = 5;
            this.txt_codper.TextMarginTop = 0;
            this.txt_codper.TextPlaceholder = "Codigo | Persona";
            this.txt_codper.UseSystemPasswordChar = false;
            this.txt_codper.WordWrap = true;
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.Transparent;
            this.button8.BackgroundImage = global::SOFTWARE_INVENTARIO.Properties.Resources.foto_01;
            this.button8.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.button8.FlatAppearance.BorderSize = 0;
            this.button8.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button8.ForeColor = System.Drawing.Color.Transparent;
            this.button8.Location = new System.Drawing.Point(145, 554);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(20, 20);
            this.button8.TabIndex = 133;
            this.button8.UseVisualStyleBackColor = false;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // PBox1
            // 
            this.PBox1.BaseColor = System.Drawing.Color.White;
            this.PBox1.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.SinFoto;
            this.PBox1.Location = new System.Drawing.Point(105, 448);
            this.PBox1.Name = "PBox1";
            this.PBox1.Size = new System.Drawing.Size(100, 100);
            this.PBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.PBox1.TabIndex = 134;
            this.PBox1.TabStop = false;
            this.PBox1.UseTransfarantBackground = false;
            // 
            // cbx_Cargo
            // 
            this.cbx_Cargo.BackColor = System.Drawing.Color.Transparent;
            this.cbx_Cargo.BorderColor = System.Drawing.Color.Silver;
            this.cbx_Cargo.BorderRadius = 4;
            this.cbx_Cargo.BorderThickness = 2;
            this.cbx_Cargo.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbx_Cargo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbx_Cargo.FocusedColor = System.Drawing.Color.Empty;
            this.cbx_Cargo.FocusedState.Parent = this.cbx_Cargo;
            this.cbx_Cargo.Font = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.cbx_Cargo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.cbx_Cargo.FormattingEnabled = true;
            this.cbx_Cargo.HoverState.Parent = this.cbx_Cargo;
            this.cbx_Cargo.ItemHeight = 30;
            this.cbx_Cargo.ItemsAppearance.Parent = this.cbx_Cargo;
            this.cbx_Cargo.Location = new System.Drawing.Point(16, 335);
            this.cbx_Cargo.Name = "cbx_Cargo";
            this.cbx_Cargo.ShadowDecoration.Parent = this.cbx_Cargo;
            this.cbx_Cargo.Size = new System.Drawing.Size(279, 36);
            this.cbx_Cargo.TabIndex = 16;
            // 
            // txt_Correo
            // 
            this.txt_Correo.AcceptsReturn = false;
            this.txt_Correo.AcceptsTab = false;
            this.txt_Correo.AnimationSpeed = 200;
            this.txt_Correo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Correo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Correo.BackColor = System.Drawing.Color.Transparent;
            this.txt_Correo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Correo.BackgroundImage")));
            this.txt_Correo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            this.txt_Correo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Correo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            this.txt_Correo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Correo.BorderRadius = 8;
            this.txt_Correo.BorderThickness = 2;
            this.txt_Correo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Correo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Correo.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Correo.DefaultText = "";
            this.txt_Correo.FillColor = System.Drawing.Color.White;
            this.txt_Correo.ForeColor = System.Drawing.Color.Gray;
            this.txt_Correo.HideSelection = true;
            this.txt_Correo.IconLeft = null;
            this.txt_Correo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Correo.IconPadding = 10;
            this.txt_Correo.IconRight = null;
            this.txt_Correo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Correo.Lines = new string[0];
            this.txt_Correo.Location = new System.Drawing.Point(16, 291);
            this.txt_Correo.MaxLength = 32767;
            this.txt_Correo.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Correo.Modified = false;
            this.txt_Correo.Multiline = false;
            this.txt_Correo.Name = "txt_Correo";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Correo.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Correo.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Correo.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Gray;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Correo.OnIdleState = stateProperties8;
            this.txt_Correo.PasswordChar = '\0';
            this.txt_Correo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Correo.PlaceholderText = "Correo";
            this.txt_Correo.ReadOnly = false;
            this.txt_Correo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Correo.SelectedText = "";
            this.txt_Correo.SelectionLength = 0;
            this.txt_Correo.SelectionStart = 0;
            this.txt_Correo.ShortcutsEnabled = true;
            this.txt_Correo.Size = new System.Drawing.Size(279, 38);
            this.txt_Correo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Correo.TabIndex = 15;
            this.txt_Correo.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Correo.TextMarginBottom = 0;
            this.txt_Correo.TextMarginLeft = 5;
            this.txt_Correo.TextMarginTop = 0;
            this.txt_Correo.TextPlaceholder = "Correo";
            this.txt_Correo.UseSystemPasswordChar = false;
            this.txt_Correo.WordWrap = true;
            // 
            // txt_Telefono
            // 
            this.txt_Telefono.AcceptsReturn = false;
            this.txt_Telefono.AcceptsTab = false;
            this.txt_Telefono.AnimationSpeed = 200;
            this.txt_Telefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Telefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Telefono.BackColor = System.Drawing.Color.Transparent;
            this.txt_Telefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Telefono.BackgroundImage")));
            this.txt_Telefono.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            this.txt_Telefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Telefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            this.txt_Telefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Telefono.BorderRadius = 8;
            this.txt_Telefono.BorderThickness = 2;
            this.txt_Telefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Telefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Telefono.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Telefono.DefaultText = "";
            this.txt_Telefono.FillColor = System.Drawing.Color.White;
            this.txt_Telefono.ForeColor = System.Drawing.Color.Gray;
            this.txt_Telefono.HideSelection = true;
            this.txt_Telefono.IconLeft = null;
            this.txt_Telefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Telefono.IconPadding = 10;
            this.txt_Telefono.IconRight = null;
            this.txt_Telefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Telefono.Lines = new string[0];
            this.txt_Telefono.Location = new System.Drawing.Point(16, 247);
            this.txt_Telefono.MaxLength = 32767;
            this.txt_Telefono.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Telefono.Modified = false;
            this.txt_Telefono.Multiline = false;
            this.txt_Telefono.Name = "txt_Telefono";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Telefono.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Telefono.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Telefono.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Gray;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Telefono.OnIdleState = stateProperties12;
            this.txt_Telefono.PasswordChar = '\0';
            this.txt_Telefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Telefono.PlaceholderText = "Telefono";
            this.txt_Telefono.ReadOnly = false;
            this.txt_Telefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Telefono.SelectedText = "";
            this.txt_Telefono.SelectionLength = 0;
            this.txt_Telefono.SelectionStart = 0;
            this.txt_Telefono.ShortcutsEnabled = true;
            this.txt_Telefono.Size = new System.Drawing.Size(279, 38);
            this.txt_Telefono.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Telefono.TabIndex = 14;
            this.txt_Telefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Telefono.TextMarginBottom = 0;
            this.txt_Telefono.TextMarginLeft = 5;
            this.txt_Telefono.TextMarginTop = 0;
            this.txt_Telefono.TextPlaceholder = "Telefono";
            this.txt_Telefono.UseSystemPasswordChar = false;
            this.txt_Telefono.WordWrap = true;
            // 
            // txt_Direccion
            // 
            this.txt_Direccion.AcceptsReturn = false;
            this.txt_Direccion.AcceptsTab = false;
            this.txt_Direccion.AnimationSpeed = 200;
            this.txt_Direccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Direccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Direccion.BackColor = System.Drawing.Color.Transparent;
            this.txt_Direccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Direccion.BackgroundImage")));
            this.txt_Direccion.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            this.txt_Direccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Direccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            this.txt_Direccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Direccion.BorderRadius = 8;
            this.txt_Direccion.BorderThickness = 2;
            this.txt_Direccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Direccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Direccion.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Direccion.DefaultText = "";
            this.txt_Direccion.FillColor = System.Drawing.Color.White;
            this.txt_Direccion.ForeColor = System.Drawing.Color.Gray;
            this.txt_Direccion.HideSelection = true;
            this.txt_Direccion.IconLeft = null;
            this.txt_Direccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Direccion.IconPadding = 10;
            this.txt_Direccion.IconRight = null;
            this.txt_Direccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Direccion.Lines = new string[0];
            this.txt_Direccion.Location = new System.Drawing.Point(16, 203);
            this.txt_Direccion.MaxLength = 32767;
            this.txt_Direccion.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Direccion.Modified = false;
            this.txt_Direccion.Multiline = false;
            this.txt_Direccion.Name = "txt_Direccion";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Direccion.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Direccion.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Direccion.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Gray;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Direccion.OnIdleState = stateProperties16;
            this.txt_Direccion.PasswordChar = '\0';
            this.txt_Direccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Direccion.PlaceholderText = "Dirección";
            this.txt_Direccion.ReadOnly = false;
            this.txt_Direccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Direccion.SelectedText = "";
            this.txt_Direccion.SelectionLength = 0;
            this.txt_Direccion.SelectionStart = 0;
            this.txt_Direccion.ShortcutsEnabled = true;
            this.txt_Direccion.Size = new System.Drawing.Size(279, 38);
            this.txt_Direccion.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Direccion.TabIndex = 13;
            this.txt_Direccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Direccion.TextMarginBottom = 0;
            this.txt_Direccion.TextMarginLeft = 5;
            this.txt_Direccion.TextMarginTop = 0;
            this.txt_Direccion.TextPlaceholder = "Dirección";
            this.txt_Direccion.UseSystemPasswordChar = false;
            this.txt_Direccion.WordWrap = true;
            // 
            // Btn_Actualizar
            // 
            this.Btn_Actualizar.AnimationHoverSpeed = 0.01F;
            this.Btn_Actualizar.AnimationSpeed = 0.01F;
            this.Btn_Actualizar.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Actualizar.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Actualizar.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.BorderSize = 3;
            this.Btn_Actualizar.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Actualizar.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Actualizar.CheckedImage")));
            this.Btn_Actualizar.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Actualizar.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Actualizar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Actualizar.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONupdate;
            this.Btn_Actualizar.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Actualizar.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Actualizar.LineColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.Location = new System.Drawing.Point(239, 621);
            this.Btn_Actualizar.Name = "Btn_Actualizar";
            this.Btn_Actualizar.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Actualizar.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Actualizar.OnHoverImage = null;
            this.Btn_Actualizar.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Actualizar.Radius = 2;
            this.Btn_Actualizar.Size = new System.Drawing.Size(44, 44);
            this.Btn_Actualizar.TabIndex = 10;
            this.Btn_Actualizar.TextOffsetX = 10;
            this.Btn_Actualizar.Click += new System.EventHandler(this.Btn_Actualizar_Click);
            // 
            // Btn_Eliminar
            // 
            this.Btn_Eliminar.AnimationHoverSpeed = 0.01F;
            this.Btn_Eliminar.AnimationSpeed = 0.01F;
            this.Btn_Eliminar.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Eliminar.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Eliminar.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.BorderSize = 3;
            this.Btn_Eliminar.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Eliminar.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Eliminar.CheckedImage")));
            this.Btn_Eliminar.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Eliminar.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Eliminar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Eliminar.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONdelete;
            this.Btn_Eliminar.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Eliminar.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Eliminar.LineColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.Location = new System.Drawing.Point(168, 621);
            this.Btn_Eliminar.Name = "Btn_Eliminar";
            this.Btn_Eliminar.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Eliminar.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Eliminar.OnHoverImage = null;
            this.Btn_Eliminar.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Eliminar.Radius = 2;
            this.Btn_Eliminar.Size = new System.Drawing.Size(44, 44);
            this.Btn_Eliminar.TabIndex = 9;
            this.Btn_Eliminar.TextOffsetX = 10;
            this.Btn_Eliminar.Click += new System.EventHandler(this.Btn_Eliminar_Click);
            // 
            // Btn_Guardar
            // 
            this.Btn_Guardar.AnimationHoverSpeed = 0.01F;
            this.Btn_Guardar.AnimationSpeed = 0.01F;
            this.Btn_Guardar.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Guardar.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Guardar.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.BorderSize = 3;
            this.Btn_Guardar.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Guardar.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Guardar.CheckedImage")));
            this.Btn_Guardar.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Guardar.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Guardar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Guardar.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONguardar2;
            this.Btn_Guardar.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Guardar.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Guardar.LineColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.Location = new System.Drawing.Point(97, 621);
            this.Btn_Guardar.Name = "Btn_Guardar";
            this.Btn_Guardar.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Guardar.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Guardar.OnHoverImage = null;
            this.Btn_Guardar.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Guardar.Radius = 2;
            this.Btn_Guardar.Size = new System.Drawing.Size(44, 44);
            this.Btn_Guardar.TabIndex = 8;
            this.Btn_Guardar.TextOffsetX = 10;
            this.Btn_Guardar.Click += new System.EventHandler(this.Btn_Guardar_Click);
            // 
            // Btn_Nuevo
            // 
            this.Btn_Nuevo.AnimationHoverSpeed = 0.01F;
            this.Btn_Nuevo.AnimationSpeed = 0.01F;
            this.Btn_Nuevo.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Nuevo.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Nuevo.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.BorderSize = 3;
            this.Btn_Nuevo.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Nuevo.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Nuevo.CheckedImage")));
            this.Btn_Nuevo.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Nuevo.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Nuevo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Nuevo.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONadd1;
            this.Btn_Nuevo.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Nuevo.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Nuevo.LineColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.Location = new System.Drawing.Point(26, 621);
            this.Btn_Nuevo.Name = "Btn_Nuevo";
            this.Btn_Nuevo.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Nuevo.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Nuevo.OnHoverImage = null;
            this.Btn_Nuevo.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Nuevo.Radius = 2;
            this.Btn_Nuevo.Size = new System.Drawing.Size(44, 44);
            this.Btn_Nuevo.TabIndex = 7;
            this.Btn_Nuevo.TextOffsetX = 10;
            this.Btn_Nuevo.Click += new System.EventHandler(this.Btn_Nuevo_Click);
            // 
            // Btn_Salir
            // 
            this.Btn_Salir.BackgroundImage = global::SOFTWARE_INVENTARIO.Properties.Resources.cerrar_Mesa_de_trabajo_1;
            this.Btn_Salir.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.Btn_Salir.BorderColor = System.Drawing.Color.Transparent;
            this.Btn_Salir.BorderRadius = 6;
            this.Btn_Salir.CheckedState.Parent = this.Btn_Salir;
            this.Btn_Salir.CustomImages.Parent = this.Btn_Salir;
            this.Btn_Salir.FillColor = System.Drawing.Color.Transparent;
            this.Btn_Salir.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Btn_Salir.ForeColor = System.Drawing.Color.White;
            this.Btn_Salir.HoverState.Parent = this.Btn_Salir;
            this.Btn_Salir.Location = new System.Drawing.Point(270, 17);
            this.Btn_Salir.Name = "Btn_Salir";
            this.Btn_Salir.PressedColor = System.Drawing.Color.White;
            this.Btn_Salir.ShadowDecoration.Parent = this.Btn_Salir;
            this.Btn_Salir.Size = new System.Drawing.Size(25, 25);
            this.Btn_Salir.TabIndex = 11;
            this.Btn_Salir.Click += new System.EventHandler(this.Btn_Salir_Click);
            // 
            // txt_Apellido
            // 
            this.txt_Apellido.AcceptsReturn = false;
            this.txt_Apellido.AcceptsTab = false;
            this.txt_Apellido.AnimationSpeed = 200;
            this.txt_Apellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Apellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Apellido.BackColor = System.Drawing.Color.Transparent;
            this.txt_Apellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Apellido.BackgroundImage")));
            this.txt_Apellido.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            this.txt_Apellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Apellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            this.txt_Apellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Apellido.BorderRadius = 8;
            this.txt_Apellido.BorderThickness = 2;
            this.txt_Apellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Apellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Apellido.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Apellido.DefaultText = "";
            this.txt_Apellido.FillColor = System.Drawing.Color.White;
            this.txt_Apellido.ForeColor = System.Drawing.Color.Gray;
            this.txt_Apellido.HideSelection = true;
            this.txt_Apellido.IconLeft = null;
            this.txt_Apellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Apellido.IconPadding = 10;
            this.txt_Apellido.IconRight = null;
            this.txt_Apellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Apellido.Lines = new string[0];
            this.txt_Apellido.Location = new System.Drawing.Point(16, 159);
            this.txt_Apellido.MaxLength = 32767;
            this.txt_Apellido.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Apellido.Modified = false;
            this.txt_Apellido.Multiline = false;
            this.txt_Apellido.Name = "txt_Apellido";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Apellido.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Apellido.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Apellido.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Gray;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Apellido.OnIdleState = stateProperties20;
            this.txt_Apellido.PasswordChar = '\0';
            this.txt_Apellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Apellido.PlaceholderText = "Apellido";
            this.txt_Apellido.ReadOnly = false;
            this.txt_Apellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Apellido.SelectedText = "";
            this.txt_Apellido.SelectionLength = 0;
            this.txt_Apellido.SelectionStart = 0;
            this.txt_Apellido.ShortcutsEnabled = true;
            this.txt_Apellido.Size = new System.Drawing.Size(279, 38);
            this.txt_Apellido.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Apellido.TabIndex = 3;
            this.txt_Apellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Apellido.TextMarginBottom = 0;
            this.txt_Apellido.TextMarginLeft = 5;
            this.txt_Apellido.TextMarginTop = 0;
            this.txt_Apellido.TextPlaceholder = "Apellido";
            this.txt_Apellido.UseSystemPasswordChar = false;
            this.txt_Apellido.WordWrap = true;
            // 
            // txt_Nombre
            // 
            this.txt_Nombre.AcceptsReturn = false;
            this.txt_Nombre.AcceptsTab = false;
            this.txt_Nombre.AnimationSpeed = 200;
            this.txt_Nombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Nombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Nombre.BackColor = System.Drawing.Color.Transparent;
            this.txt_Nombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Nombre.BackgroundImage")));
            this.txt_Nombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            this.txt_Nombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Nombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            this.txt_Nombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Nombre.BorderRadius = 8;
            this.txt_Nombre.BorderThickness = 2;
            this.txt_Nombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Nombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Nombre.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Nombre.DefaultText = "";
            this.txt_Nombre.FillColor = System.Drawing.Color.White;
            this.txt_Nombre.ForeColor = System.Drawing.Color.Gray;
            this.txt_Nombre.HideSelection = true;
            this.txt_Nombre.IconLeft = null;
            this.txt_Nombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Nombre.IconPadding = 10;
            this.txt_Nombre.IconRight = null;
            this.txt_Nombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Nombre.Lines = new string[0];
            this.txt_Nombre.Location = new System.Drawing.Point(16, 115);
            this.txt_Nombre.MaxLength = 32767;
            this.txt_Nombre.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Nombre.Modified = false;
            this.txt_Nombre.Multiline = false;
            this.txt_Nombre.Name = "txt_Nombre";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Nombre.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Nombre.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Nombre.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Gray;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Nombre.OnIdleState = stateProperties24;
            this.txt_Nombre.PasswordChar = '\0';
            this.txt_Nombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Nombre.PlaceholderText = "Nombre ";
            this.txt_Nombre.ReadOnly = false;
            this.txt_Nombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Nombre.SelectedText = "";
            this.txt_Nombre.SelectionLength = 0;
            this.txt_Nombre.SelectionStart = 0;
            this.txt_Nombre.ShortcutsEnabled = true;
            this.txt_Nombre.Size = new System.Drawing.Size(279, 38);
            this.txt_Nombre.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Nombre.TabIndex = 2;
            this.txt_Nombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Nombre.TextMarginBottom = 0;
            this.txt_Nombre.TextMarginLeft = 5;
            this.txt_Nombre.TextMarginTop = 0;
            this.txt_Nombre.TextPlaceholder = "Nombre ";
            this.txt_Nombre.UseSystemPasswordChar = false;
            this.txt_Nombre.WordWrap = true;
            this.txt_Nombre.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_Nombre_KeyPress);
            // 
            // txt_Codigo
            // 
            this.txt_Codigo.AcceptsReturn = false;
            this.txt_Codigo.AcceptsTab = false;
            this.txt_Codigo.AnimationSpeed = 200;
            this.txt_Codigo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Codigo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Codigo.BackColor = System.Drawing.Color.Transparent;
            this.txt_Codigo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Codigo.BackgroundImage")));
            this.txt_Codigo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            this.txt_Codigo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Codigo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            this.txt_Codigo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Codigo.BorderRadius = 8;
            this.txt_Codigo.BorderThickness = 2;
            this.txt_Codigo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Codigo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Codigo.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Codigo.DefaultText = "";
            this.txt_Codigo.FillColor = System.Drawing.Color.White;
            this.txt_Codigo.ForeColor = System.Drawing.Color.Gray;
            this.txt_Codigo.HideSelection = true;
            this.txt_Codigo.IconLeft = null;
            this.txt_Codigo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Codigo.IconPadding = 10;
            this.txt_Codigo.IconRight = null;
            this.txt_Codigo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Codigo.Lines = new string[0];
            this.txt_Codigo.Location = new System.Drawing.Point(16, 71);
            this.txt_Codigo.MaxLength = 32767;
            this.txt_Codigo.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Codigo.Modified = false;
            this.txt_Codigo.Multiline = false;
            this.txt_Codigo.Name = "txt_Codigo";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(184)))), ((int)(((byte)(255)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Codigo.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Codigo.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(118)))), ((int)(((byte)(174)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Codigo.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Gray;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Codigo.OnIdleState = stateProperties28;
            this.txt_Codigo.PasswordChar = '\0';
            this.txt_Codigo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Codigo.PlaceholderText = "ID Persona 001.";
            this.txt_Codigo.ReadOnly = false;
            this.txt_Codigo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Codigo.SelectedText = "";
            this.txt_Codigo.SelectionLength = 0;
            this.txt_Codigo.SelectionStart = 0;
            this.txt_Codigo.ShortcutsEnabled = true;
            this.txt_Codigo.Size = new System.Drawing.Size(279, 38);
            this.txt_Codigo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Codigo.TabIndex = 0;
            this.txt_Codigo.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Codigo.TextMarginBottom = 0;
            this.txt_Codigo.TextMarginLeft = 5;
            this.txt_Codigo.TextMarginTop = 0;
            this.txt_Codigo.TextPlaceholder = "ID Persona 001.";
            this.txt_Codigo.UseSystemPasswordChar = false;
            this.txt_Codigo.WordWrap = true;
            this.txt_Codigo.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_Codigo_KeyPress);
            this.txt_Codigo.Validated += new System.EventHandler(this.txt_Codigo_Validated);
            // 
            // Txt_Buscar
            // 
            this.Txt_Buscar.AcceptsReturn = false;
            this.Txt_Buscar.AcceptsTab = false;
            this.Txt_Buscar.AnimationSpeed = 200;
            this.Txt_Buscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Txt_Buscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Txt_Buscar.BackColor = System.Drawing.Color.Transparent;
            this.Txt_Buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Txt_Buscar.BackgroundImage")));
            this.Txt_Buscar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.Txt_Buscar.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.Txt_Buscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Txt_Buscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.Txt_Buscar.BorderColorIdle = System.Drawing.Color.Silver;
            this.Txt_Buscar.BorderRadius = 8;
            this.Txt_Buscar.BorderThickness = 2;
            this.Txt_Buscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Txt_Buscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Txt_Buscar.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.Txt_Buscar.DefaultText = "";
            this.Txt_Buscar.FillColor = System.Drawing.Color.White;
            this.Txt_Buscar.ForeColor = System.Drawing.Color.Gray;
            this.Txt_Buscar.HideSelection = true;
            this.Txt_Buscar.IconLeft = null;
            this.Txt_Buscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Txt_Buscar.IconPadding = 10;
            this.Txt_Buscar.IconRight = null;
            this.Txt_Buscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Txt_Buscar.Lines = new string[0];
            this.Txt_Buscar.Location = new System.Drawing.Point(282, 653);
            this.Txt_Buscar.MaxLength = 32767;
            this.Txt_Buscar.MinimumSize = new System.Drawing.Size(100, 35);
            this.Txt_Buscar.Modified = false;
            this.Txt_Buscar.Multiline = false;
            this.Txt_Buscar.Name = "Txt_Buscar";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Txt_Buscar.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Empty;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Txt_Buscar.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Txt_Buscar.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Gray;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Txt_Buscar.OnIdleState = stateProperties32;
            this.Txt_Buscar.PasswordChar = '\0';
            this.Txt_Buscar.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Txt_Buscar.PlaceholderText = "Buscar...";
            this.Txt_Buscar.ReadOnly = false;
            this.Txt_Buscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Txt_Buscar.SelectedText = "";
            this.Txt_Buscar.SelectionLength = 0;
            this.Txt_Buscar.SelectionStart = 0;
            this.Txt_Buscar.ShortcutsEnabled = true;
            this.Txt_Buscar.Size = new System.Drawing.Size(372, 38);
            this.Txt_Buscar.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Txt_Buscar.TabIndex = 160;
            this.Txt_Buscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Txt_Buscar.TextMarginBottom = 0;
            this.Txt_Buscar.TextMarginLeft = 5;
            this.Txt_Buscar.TextMarginTop = 0;
            this.Txt_Buscar.TextPlaceholder = "Buscar...";
            this.Txt_Buscar.UseSystemPasswordChar = false;
            this.Txt_Buscar.WordWrap = true;
            this.Txt_Buscar.KeyUp += new System.Windows.Forms.KeyEventHandler(this.Txt_Buscar_KeyUp);
            // 
            // Ant
            // 
            this.Ant.AnimationHoverSpeed = 0.01F;
            this.Ant.AnimationSpeed = 0.01F;
            this.Ant.BackColor = System.Drawing.Color.Transparent;
            this.Ant.BaseColor = System.Drawing.Color.LightGray;
            this.Ant.BorderColor = System.Drawing.Color.Empty;
            this.Ant.BorderSize = 3;
            this.Ant.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Ant.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Ant.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Ant.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Ant.CheckedImage")));
            this.Ant.CheckedLineColor = System.Drawing.Color.Empty;
            this.Ant.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Ant.FocusedColor = System.Drawing.Color.Empty;
            this.Ant.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Ant.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Ant.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.Pri_01;
            this.Ant.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Ant.ImageSize = new System.Drawing.Size(40, 40);
            this.Ant.LineColor = System.Drawing.Color.Empty;
            this.Ant.Location = new System.Drawing.Point(6, 650);
            this.Ant.Name = "Ant";
            this.Ant.OnHoverBaseColor = System.Drawing.Color.White;
            this.Ant.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Ant.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ant.OnHoverImage = null;
            this.Ant.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Ant.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ant.Radius = 9;
            this.Ant.Size = new System.Drawing.Size(44, 44);
            this.Ant.TabIndex = 155;
            this.Ant.TextOffsetX = 10;
            this.Ant.Click += new System.EventHandler(this.Ant_Click);
            // 
            // Sig
            // 
            this.Sig.AnimationHoverSpeed = 0.01F;
            this.Sig.AnimationSpeed = 0.01F;
            this.Sig.BackColor = System.Drawing.Color.Transparent;
            this.Sig.BaseColor = System.Drawing.Color.LightGray;
            this.Sig.BorderColor = System.Drawing.Color.Empty;
            this.Sig.BorderSize = 3;
            this.Sig.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Sig.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Sig.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Sig.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Sig.CheckedImage")));
            this.Sig.CheckedLineColor = System.Drawing.Color.Empty;
            this.Sig.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Sig.FocusedColor = System.Drawing.Color.Empty;
            this.Sig.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Sig.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Sig.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.Ult_01;
            this.Sig.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Sig.ImageSize = new System.Drawing.Size(40, 40);
            this.Sig.LineColor = System.Drawing.Color.Empty;
            this.Sig.Location = new System.Drawing.Point(56, 650);
            this.Sig.Name = "Sig";
            this.Sig.OnHoverBaseColor = System.Drawing.Color.White;
            this.Sig.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Sig.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Sig.OnHoverImage = null;
            this.Sig.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Sig.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Sig.Radius = 9;
            this.Sig.Size = new System.Drawing.Size(44, 44);
            this.Sig.TabIndex = 154;
            this.Sig.TextOffsetX = 10;
            this.Sig.Click += new System.EventHandler(this.Sig_Click);
            // 
            // Pri
            // 
            this.Pri.AnimationHoverSpeed = 0.01F;
            this.Pri.AnimationSpeed = 0.01F;
            this.Pri.BackColor = System.Drawing.Color.Transparent;
            this.Pri.BaseColor = System.Drawing.Color.LightGray;
            this.Pri.BorderColor = System.Drawing.Color.Empty;
            this.Pri.BorderSize = 3;
            this.Pri.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Pri.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Pri.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Pri.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Pri.CheckedImage")));
            this.Pri.CheckedLineColor = System.Drawing.Color.Empty;
            this.Pri.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Pri.FocusedColor = System.Drawing.Color.Empty;
            this.Pri.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Pri.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Pri.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.Ant_01;
            this.Pri.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Pri.ImageSize = new System.Drawing.Size(40, 40);
            this.Pri.LineColor = System.Drawing.Color.Empty;
            this.Pri.Location = new System.Drawing.Point(837, 650);
            this.Pri.Name = "Pri";
            this.Pri.OnHoverBaseColor = System.Drawing.Color.White;
            this.Pri.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Pri.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Pri.OnHoverImage = null;
            this.Pri.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Pri.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Pri.Radius = 9;
            this.Pri.Size = new System.Drawing.Size(44, 44);
            this.Pri.TabIndex = 153;
            this.Pri.TextOffsetX = 10;
            this.Pri.Click += new System.EventHandler(this.Pri_Click);
            // 
            // Ult
            // 
            this.Ult.AnimationHoverSpeed = 0.01F;
            this.Ult.AnimationSpeed = 0.01F;
            this.Ult.BackColor = System.Drawing.Color.Transparent;
            this.Ult.BaseColor = System.Drawing.Color.LightGray;
            this.Ult.BorderColor = System.Drawing.Color.Empty;
            this.Ult.BorderSize = 3;
            this.Ult.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Ult.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Ult.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Ult.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Ult.CheckedImage")));
            this.Ult.CheckedLineColor = System.Drawing.Color.Empty;
            this.Ult.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Ult.FocusedColor = System.Drawing.Color.Empty;
            this.Ult.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Ult.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Ult.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.sig1_01;
            this.Ult.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Ult.ImageSize = new System.Drawing.Size(40, 40);
            this.Ult.LineColor = System.Drawing.Color.Empty;
            this.Ult.Location = new System.Drawing.Point(887, 650);
            this.Ult.Name = "Ult";
            this.Ult.OnHoverBaseColor = System.Drawing.Color.White;
            this.Ult.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Ult.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ult.OnHoverImage = null;
            this.Ult.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Ult.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ult.Radius = 9;
            this.Ult.Size = new System.Drawing.Size(44, 44);
            this.Ult.TabIndex = 152;
            this.Ult.TextOffsetX = 10;
            this.Ult.Click += new System.EventHandler(this.Ult_Click);
            // 
            // guna2Elipse1
            // 
            this.guna2Elipse1.BorderRadius = 8;
            this.guna2Elipse1.TargetControl = this;
            // 
            // guna2Elipse2
            // 
            this.guna2Elipse2.BorderRadius = 8;
            this.guna2Elipse2.TargetControl = this.dataGridView1;
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // FormPersonas
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1266, 700);
            this.Controls.Add(this.Txt_Buscar);
            this.Controls.Add(this.Ant);
            this.Controls.Add(this.Sig);
            this.Controls.Add(this.Pri);
            this.Controls.Add(this.Ult);
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.bunifuGroupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormPersonas";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormPersonas";
            this.Load += new System.EventHandler(this.FormPersonas_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuShadowPanel groupBox1;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Actualizar;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Eliminar;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Guardar;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Nuevo;
        private Guna.UI2.WinForms.Guna2Button Btn_Salir;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Apellido;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Nombre;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Codigo;
        private Guna.UI.WinForms.GunaAdvenceButton Pri;
        private Guna.UI.WinForms.GunaAdvenceButton Ult;
        private Guna.UI.WinForms.GunaAdvenceButton Ant;
        private Guna.UI.WinForms.GunaAdvenceButton Sig;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Correo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Telefono;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Direccion;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Txt_Buscar;
        private Guna.UI2.WinForms.Guna2ComboBox cbx_Cargo;
        private System.Windows.Forms.Button button8;
        private Guna.UI.WinForms.GunaCirclePictureBox PBox1;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse1;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse2;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_codper;
        private Guna.UI2.WinForms.Guna2ShadowForm guna2ShadowForm1;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
    }
}