
namespace SOFTWARE_INVENTARIO
{
    partial class FormProducto
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormProducto));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.groupBox1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txt_Elemento = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Estado = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Btn_Actualizar = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Eliminar = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Guardar = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Nuevo = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Salir = new Guna.UI2.WinForms.Guna2Button();
            this.cbx_Categoria = new Guna.UI2.WinForms.Guna2ComboBox();
            this.txt_fecha = new Guna.UI2.WinForms.Guna2DateTimePicker();
            this.txt_Descripcion = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Cantidad = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Nombre = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_Codigo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.guna2Elipse1 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.dataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.guna2Elipse2 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.Ant = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Sig = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Pri = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Ult = new Guna.UI.WinForms.GunaAdvenceButton();
            this.Btn_Cerrar = new Guna.UI2.WinForms.Guna2Button();
            this.guna2ShadowForm1 = new Guna.UI2.WinForms.Guna2ShadowForm(this.components);
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.Txt_Buscar = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.groupBox1.BorderRadius = 8;
            this.groupBox1.BorderThickness = 1;
            this.groupBox1.Controls.Add(this.txt_Elemento);
            this.groupBox1.Controls.Add(this.txt_Estado);
            this.groupBox1.Controls.Add(this.Btn_Actualizar);
            this.groupBox1.Controls.Add(this.Btn_Eliminar);
            this.groupBox1.Controls.Add(this.Btn_Guardar);
            this.groupBox1.Controls.Add(this.Btn_Nuevo);
            this.groupBox1.Controls.Add(this.Btn_Salir);
            this.groupBox1.Controls.Add(this.cbx_Categoria);
            this.groupBox1.Controls.Add(this.txt_fecha);
            this.groupBox1.Controls.Add(this.txt_Descripcion);
            this.groupBox1.Controls.Add(this.txt_Cantidad);
            this.groupBox1.Controls.Add(this.txt_Nombre);
            this.groupBox1.Controls.Add(this.txt_Codigo);
            this.groupBox1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.groupBox1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.groupBox1.Location = new System.Drawing.Point(6, 13);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.PanelColor = System.Drawing.Color.White;
            this.groupBox1.PanelColor2 = System.Drawing.Color.White;
            this.groupBox1.ShadowColor = System.Drawing.Color.DarkGray;
            this.groupBox1.ShadowDept = 2;
            this.groupBox1.ShadowDepth = 2;
            this.groupBox1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.groupBox1.ShadowTopLeftVisible = false;
            this.groupBox1.Size = new System.Drawing.Size(311, 681);
            this.groupBox1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.groupBox1.TabIndex = 0;
            // 
            // txt_Elemento
            // 
            this.txt_Elemento.AcceptsReturn = false;
            this.txt_Elemento.AcceptsTab = false;
            this.txt_Elemento.AnimationSpeed = 200;
            this.txt_Elemento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Elemento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Elemento.BackColor = System.Drawing.Color.Transparent;
            this.txt_Elemento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Elemento.BackgroundImage")));
            this.txt_Elemento.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.txt_Elemento.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.txt_Elemento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Elemento.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.txt_Elemento.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Elemento.BorderRadius = 8;
            this.txt_Elemento.BorderThickness = 2;
            this.txt_Elemento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Elemento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Elemento.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Elemento.DefaultText = "";
            this.txt_Elemento.FillColor = System.Drawing.Color.White;
            this.txt_Elemento.ForeColor = System.Drawing.Color.Gray;
            this.txt_Elemento.HideSelection = true;
            this.txt_Elemento.IconLeft = null;
            this.txt_Elemento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Elemento.IconPadding = 10;
            this.txt_Elemento.IconRight = null;
            this.txt_Elemento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Elemento.Lines = new string[0];
            this.txt_Elemento.Location = new System.Drawing.Point(16, 364);
            this.txt_Elemento.MaxLength = 32767;
            this.txt_Elemento.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Elemento.Modified = false;
            this.txt_Elemento.Multiline = false;
            this.txt_Elemento.Name = "txt_Elemento";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Elemento.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Elemento.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Elemento.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Gray;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Elemento.OnIdleState = stateProperties4;
            this.txt_Elemento.PasswordChar = '\0';
            this.txt_Elemento.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Elemento.PlaceholderText = "codigo y nombre";
            this.txt_Elemento.ReadOnly = false;
            this.txt_Elemento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Elemento.SelectedText = "";
            this.txt_Elemento.SelectionLength = 0;
            this.txt_Elemento.SelectionStart = 0;
            this.txt_Elemento.ShortcutsEnabled = true;
            this.txt_Elemento.Size = new System.Drawing.Size(279, 38);
            this.txt_Elemento.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Elemento.TabIndex = 12;
            this.txt_Elemento.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Elemento.TextMarginBottom = 0;
            this.txt_Elemento.TextMarginLeft = 5;
            this.txt_Elemento.TextMarginTop = 0;
            this.txt_Elemento.TextPlaceholder = "codigo y nombre";
            this.txt_Elemento.UseSystemPasswordChar = false;
            this.txt_Elemento.WordWrap = true;
            // 
            // txt_Estado
            // 
            this.txt_Estado.AcceptsReturn = false;
            this.txt_Estado.AcceptsTab = false;
            this.txt_Estado.AnimationSpeed = 200;
            this.txt_Estado.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Estado.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Estado.BackColor = System.Drawing.Color.Transparent;
            this.txt_Estado.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Estado.BackgroundImage")));
            this.txt_Estado.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.txt_Estado.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.txt_Estado.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Estado.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.txt_Estado.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Estado.BorderRadius = 8;
            this.txt_Estado.BorderThickness = 2;
            this.txt_Estado.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Estado.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Estado.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Estado.DefaultText = "";
            this.txt_Estado.FillColor = System.Drawing.Color.White;
            this.txt_Estado.ForeColor = System.Drawing.Color.Gray;
            this.txt_Estado.HideSelection = true;
            this.txt_Estado.IconLeft = null;
            this.txt_Estado.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Estado.IconPadding = 10;
            this.txt_Estado.IconRight = null;
            this.txt_Estado.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Estado.Lines = new string[0];
            this.txt_Estado.Location = new System.Drawing.Point(16, 408);
            this.txt_Estado.MaxLength = 32767;
            this.txt_Estado.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Estado.Modified = false;
            this.txt_Estado.Multiline = false;
            this.txt_Estado.Name = "txt_Estado";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Estado.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Estado.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Estado.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Gray;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Estado.OnIdleState = stateProperties8;
            this.txt_Estado.PasswordChar = '\0';
            this.txt_Estado.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Estado.PlaceholderText = "Estado";
            this.txt_Estado.ReadOnly = false;
            this.txt_Estado.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Estado.SelectedText = "";
            this.txt_Estado.SelectionLength = 0;
            this.txt_Estado.SelectionStart = 0;
            this.txt_Estado.ShortcutsEnabled = true;
            this.txt_Estado.Size = new System.Drawing.Size(279, 38);
            this.txt_Estado.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Estado.TabIndex = 6;
            this.txt_Estado.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Estado.TextMarginBottom = 0;
            this.txt_Estado.TextMarginLeft = 5;
            this.txt_Estado.TextMarginTop = 0;
            this.txt_Estado.TextPlaceholder = "Estado";
            this.txt_Estado.UseSystemPasswordChar = false;
            this.txt_Estado.WordWrap = true;
            // 
            // Btn_Actualizar
            // 
            this.Btn_Actualizar.AnimationHoverSpeed = 0.01F;
            this.Btn_Actualizar.AnimationSpeed = 0.01F;
            this.Btn_Actualizar.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Actualizar.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Actualizar.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.BorderSize = 3;
            this.Btn_Actualizar.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Actualizar.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Actualizar.CheckedImage")));
            this.Btn_Actualizar.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Actualizar.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Actualizar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Actualizar.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONupdate;
            this.Btn_Actualizar.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Actualizar.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Actualizar.LineColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.Location = new System.Drawing.Point(239, 621);
            this.Btn_Actualizar.Name = "Btn_Actualizar";
            this.Btn_Actualizar.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Actualizar.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Actualizar.OnHoverImage = null;
            this.Btn_Actualizar.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Actualizar.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Actualizar.Radius = 2;
            this.Btn_Actualizar.Size = new System.Drawing.Size(44, 44);
            this.Btn_Actualizar.TabIndex = 10;
            this.Btn_Actualizar.TextOffsetX = 10;
            this.Btn_Actualizar.Click += new System.EventHandler(this.Btn_Actualizar_Click);
            // 
            // Btn_Eliminar
            // 
            this.Btn_Eliminar.AnimationHoverSpeed = 0.01F;
            this.Btn_Eliminar.AnimationSpeed = 0.01F;
            this.Btn_Eliminar.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Eliminar.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Eliminar.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.BorderSize = 3;
            this.Btn_Eliminar.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Eliminar.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Eliminar.CheckedImage")));
            this.Btn_Eliminar.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Eliminar.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Eliminar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Eliminar.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONdelete;
            this.Btn_Eliminar.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Eliminar.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Eliminar.LineColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.Location = new System.Drawing.Point(168, 621);
            this.Btn_Eliminar.Name = "Btn_Eliminar";
            this.Btn_Eliminar.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Eliminar.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Eliminar.OnHoverImage = null;
            this.Btn_Eliminar.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Eliminar.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Eliminar.Radius = 2;
            this.Btn_Eliminar.Size = new System.Drawing.Size(44, 44);
            this.Btn_Eliminar.TabIndex = 9;
            this.Btn_Eliminar.TextOffsetX = 10;
            this.Btn_Eliminar.Click += new System.EventHandler(this.Btn_Eliminar_Click);
            // 
            // Btn_Guardar
            // 
            this.Btn_Guardar.AnimationHoverSpeed = 0.01F;
            this.Btn_Guardar.AnimationSpeed = 0.01F;
            this.Btn_Guardar.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Guardar.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Guardar.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.BorderSize = 3;
            this.Btn_Guardar.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Guardar.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Guardar.CheckedImage")));
            this.Btn_Guardar.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Guardar.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Guardar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Guardar.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONguardar2;
            this.Btn_Guardar.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Guardar.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Guardar.LineColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.Location = new System.Drawing.Point(97, 621);
            this.Btn_Guardar.Name = "Btn_Guardar";
            this.Btn_Guardar.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Guardar.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Guardar.OnHoverImage = null;
            this.Btn_Guardar.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Guardar.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Guardar.Radius = 2;
            this.Btn_Guardar.Size = new System.Drawing.Size(44, 44);
            this.Btn_Guardar.TabIndex = 8;
            this.Btn_Guardar.TextOffsetX = 10;
            this.Btn_Guardar.Click += new System.EventHandler(this.Btn_Guardar_Click);
            // 
            // Btn_Nuevo
            // 
            this.Btn_Nuevo.AnimationHoverSpeed = 0.01F;
            this.Btn_Nuevo.AnimationSpeed = 0.01F;
            this.Btn_Nuevo.BackColor = System.Drawing.Color.Transparent;
            this.Btn_Nuevo.BaseColor = System.Drawing.Color.LightGray;
            this.Btn_Nuevo.BorderColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.BorderSize = 3;
            this.Btn_Nuevo.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Btn_Nuevo.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Btn_Nuevo.CheckedImage")));
            this.Btn_Nuevo.CheckedLineColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Btn_Nuevo.FocusedColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Btn_Nuevo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Btn_Nuevo.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.ICONadd1;
            this.Btn_Nuevo.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Btn_Nuevo.ImageSize = new System.Drawing.Size(44, 44);
            this.Btn_Nuevo.LineColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.Location = new System.Drawing.Point(26, 621);
            this.Btn_Nuevo.Name = "Btn_Nuevo";
            this.Btn_Nuevo.OnHoverBaseColor = System.Drawing.Color.White;
            this.Btn_Nuevo.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Nuevo.OnHoverImage = null;
            this.Btn_Nuevo.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Btn_Nuevo.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Btn_Nuevo.Radius = 2;
            this.Btn_Nuevo.Size = new System.Drawing.Size(44, 44);
            this.Btn_Nuevo.TabIndex = 7;
            this.Btn_Nuevo.TextOffsetX = 10;
            this.Btn_Nuevo.Click += new System.EventHandler(this.Btn_Nuevo_Click);
            // 
            // Btn_Salir
            // 
            this.Btn_Salir.BackgroundImage = global::SOFTWARE_INVENTARIO.Properties.Resources.cerrar_Mesa_de_trabajo_1;
            this.Btn_Salir.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.Btn_Salir.BorderColor = System.Drawing.Color.Transparent;
            this.Btn_Salir.BorderRadius = 6;
            this.Btn_Salir.CheckedState.Parent = this.Btn_Salir;
            this.Btn_Salir.CustomImages.Parent = this.Btn_Salir;
            this.Btn_Salir.FillColor = System.Drawing.Color.Transparent;
            this.Btn_Salir.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Btn_Salir.ForeColor = System.Drawing.Color.White;
            this.Btn_Salir.HoverState.Parent = this.Btn_Salir;
            this.Btn_Salir.Location = new System.Drawing.Point(270, 17);
            this.Btn_Salir.Name = "Btn_Salir";
            this.Btn_Salir.PressedColor = System.Drawing.Color.White;
            this.Btn_Salir.ShadowDecoration.Parent = this.Btn_Salir;
            this.Btn_Salir.Size = new System.Drawing.Size(25, 25);
            this.Btn_Salir.TabIndex = 11;
            this.Btn_Salir.Click += new System.EventHandler(this.Btn_Salir_Click);
            // 
            // cbx_Categoria
            // 
            this.cbx_Categoria.BackColor = System.Drawing.Color.Transparent;
            this.cbx_Categoria.BorderColor = System.Drawing.Color.Silver;
            this.cbx_Categoria.BorderRadius = 4;
            this.cbx_Categoria.BorderThickness = 2;
            this.cbx_Categoria.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbx_Categoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbx_Categoria.FocusedColor = System.Drawing.Color.Empty;
            this.cbx_Categoria.FocusedState.Parent = this.cbx_Categoria;
            this.cbx_Categoria.Font = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.cbx_Categoria.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.cbx_Categoria.FormattingEnabled = true;
            this.cbx_Categoria.HoverState.Parent = this.cbx_Categoria;
            this.cbx_Categoria.ItemHeight = 30;
            this.cbx_Categoria.ItemsAppearance.Parent = this.cbx_Categoria;
            this.cbx_Categoria.Location = new System.Drawing.Point(16, 203);
            this.cbx_Categoria.Name = "cbx_Categoria";
            this.cbx_Categoria.ShadowDecoration.Parent = this.cbx_Categoria;
            this.cbx_Categoria.Size = new System.Drawing.Size(279, 36);
            this.cbx_Categoria.TabIndex = 1;
            // 
            // txt_fecha
            // 
            this.txt_fecha.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_fecha.BorderRadius = 3;
            this.txt_fecha.CheckedState.Parent = this.txt_fecha;
            this.txt_fecha.FillColor = System.Drawing.Color.White;
            this.txt_fecha.Font = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_fecha.ForeColor = System.Drawing.Color.Gray;
            this.txt_fecha.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.txt_fecha.HoverState.Parent = this.txt_fecha;
            this.txt_fecha.Location = new System.Drawing.Point(16, 322);
            this.txt_fecha.MaxDate = new System.DateTime(9998, 12, 31, 0, 0, 0, 0);
            this.txt_fecha.MinDate = new System.DateTime(1753, 1, 1, 0, 0, 0, 0);
            this.txt_fecha.Name = "txt_fecha";
            this.txt_fecha.ShadowDecoration.Parent = this.txt_fecha;
            this.txt_fecha.Size = new System.Drawing.Size(279, 36);
            this.txt_fecha.TabIndex = 5;
            this.txt_fecha.Value = new System.DateTime(2021, 8, 3, 11, 6, 0, 0);
            // 
            // txt_Descripcion
            // 
            this.txt_Descripcion.AcceptsReturn = false;
            this.txt_Descripcion.AcceptsTab = false;
            this.txt_Descripcion.AnimationSpeed = 200;
            this.txt_Descripcion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Descripcion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Descripcion.BackColor = System.Drawing.Color.White;
            this.txt_Descripcion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Descripcion.BackgroundImage")));
            this.txt_Descripcion.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.txt_Descripcion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Descripcion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.txt_Descripcion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Descripcion.BorderRadius = 8;
            this.txt_Descripcion.BorderThickness = 2;
            this.txt_Descripcion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Descripcion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Descripcion.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Descripcion.DefaultText = "";
            this.txt_Descripcion.FillColor = System.Drawing.Color.White;
            this.txt_Descripcion.ForeColor = System.Drawing.Color.Gray;
            this.txt_Descripcion.HideSelection = true;
            this.txt_Descripcion.IconLeft = null;
            this.txt_Descripcion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Descripcion.IconPadding = 10;
            this.txt_Descripcion.IconRight = null;
            this.txt_Descripcion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Descripcion.Lines = new string[0];
            this.txt_Descripcion.Location = new System.Drawing.Point(16, 245);
            this.txt_Descripcion.MaxLength = 32767;
            this.txt_Descripcion.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Descripcion.Modified = false;
            this.txt_Descripcion.Multiline = true;
            this.txt_Descripcion.Name = "txt_Descripcion";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Descripcion.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Descripcion.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Descripcion.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Gray;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Descripcion.OnIdleState = stateProperties12;
            this.txt_Descripcion.PasswordChar = '\0';
            this.txt_Descripcion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Descripcion.PlaceholderText = "Descripción Producto.";
            this.txt_Descripcion.ReadOnly = false;
            this.txt_Descripcion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Descripcion.SelectedText = "";
            this.txt_Descripcion.SelectionLength = 0;
            this.txt_Descripcion.SelectionStart = 0;
            this.txt_Descripcion.ShortcutsEnabled = true;
            this.txt_Descripcion.Size = new System.Drawing.Size(279, 81);
            this.txt_Descripcion.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txt_Descripcion.TabIndex = 4;
            this.txt_Descripcion.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Descripcion.TextMarginBottom = 0;
            this.txt_Descripcion.TextMarginLeft = 5;
            this.txt_Descripcion.TextMarginTop = 0;
            this.txt_Descripcion.TextPlaceholder = "Descripción Producto.";
            this.txt_Descripcion.UseSystemPasswordChar = false;
            this.txt_Descripcion.WordWrap = true;
            // 
            // txt_Cantidad
            // 
            this.txt_Cantidad.AcceptsReturn = false;
            this.txt_Cantidad.AcceptsTab = false;
            this.txt_Cantidad.AnimationSpeed = 200;
            this.txt_Cantidad.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Cantidad.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Cantidad.BackColor = System.Drawing.Color.Transparent;
            this.txt_Cantidad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Cantidad.BackgroundImage")));
            this.txt_Cantidad.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.txt_Cantidad.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Cantidad.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.txt_Cantidad.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Cantidad.BorderRadius = 8;
            this.txt_Cantidad.BorderThickness = 2;
            this.txt_Cantidad.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Cantidad.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Cantidad.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Cantidad.DefaultText = "";
            this.txt_Cantidad.FillColor = System.Drawing.Color.White;
            this.txt_Cantidad.ForeColor = System.Drawing.Color.Gray;
            this.txt_Cantidad.HideSelection = true;
            this.txt_Cantidad.IconLeft = null;
            this.txt_Cantidad.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Cantidad.IconPadding = 10;
            this.txt_Cantidad.IconRight = null;
            this.txt_Cantidad.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Cantidad.Lines = new string[0];
            this.txt_Cantidad.Location = new System.Drawing.Point(16, 159);
            this.txt_Cantidad.MaxLength = 32767;
            this.txt_Cantidad.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Cantidad.Modified = false;
            this.txt_Cantidad.Multiline = false;
            this.txt_Cantidad.Name = "txt_Cantidad";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Cantidad.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Cantidad.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Cantidad.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Gray;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Cantidad.OnIdleState = stateProperties16;
            this.txt_Cantidad.PasswordChar = '\0';
            this.txt_Cantidad.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Cantidad.PlaceholderText = "Cantidad Prod.";
            this.txt_Cantidad.ReadOnly = false;
            this.txt_Cantidad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Cantidad.SelectedText = "";
            this.txt_Cantidad.SelectionLength = 0;
            this.txt_Cantidad.SelectionStart = 0;
            this.txt_Cantidad.ShortcutsEnabled = true;
            this.txt_Cantidad.Size = new System.Drawing.Size(279, 38);
            this.txt_Cantidad.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Cantidad.TabIndex = 3;
            this.txt_Cantidad.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Cantidad.TextMarginBottom = 0;
            this.txt_Cantidad.TextMarginLeft = 5;
            this.txt_Cantidad.TextMarginTop = 0;
            this.txt_Cantidad.TextPlaceholder = "Cantidad Prod.";
            this.txt_Cantidad.UseSystemPasswordChar = false;
            this.txt_Cantidad.WordWrap = true;
            // 
            // txt_Nombre
            // 
            this.txt_Nombre.AcceptsReturn = false;
            this.txt_Nombre.AcceptsTab = false;
            this.txt_Nombre.AnimationSpeed = 200;
            this.txt_Nombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Nombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Nombre.BackColor = System.Drawing.Color.Transparent;
            this.txt_Nombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Nombre.BackgroundImage")));
            this.txt_Nombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.txt_Nombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Nombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.txt_Nombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Nombre.BorderRadius = 8;
            this.txt_Nombre.BorderThickness = 2;
            this.txt_Nombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Nombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Nombre.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Nombre.DefaultText = "";
            this.txt_Nombre.FillColor = System.Drawing.Color.White;
            this.txt_Nombre.ForeColor = System.Drawing.Color.Gray;
            this.txt_Nombre.HideSelection = true;
            this.txt_Nombre.IconLeft = null;
            this.txt_Nombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Nombre.IconPadding = 10;
            this.txt_Nombre.IconRight = null;
            this.txt_Nombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Nombre.Lines = new string[0];
            this.txt_Nombre.Location = new System.Drawing.Point(16, 115);
            this.txt_Nombre.MaxLength = 32767;
            this.txt_Nombre.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Nombre.Modified = false;
            this.txt_Nombre.Multiline = false;
            this.txt_Nombre.Name = "txt_Nombre";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Nombre.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Nombre.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Nombre.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Gray;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Nombre.OnIdleState = stateProperties20;
            this.txt_Nombre.PasswordChar = '\0';
            this.txt_Nombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Nombre.PlaceholderText = "Nombre Producto";
            this.txt_Nombre.ReadOnly = false;
            this.txt_Nombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Nombre.SelectedText = "";
            this.txt_Nombre.SelectionLength = 0;
            this.txt_Nombre.SelectionStart = 0;
            this.txt_Nombre.ShortcutsEnabled = true;
            this.txt_Nombre.Size = new System.Drawing.Size(279, 38);
            this.txt_Nombre.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Nombre.TabIndex = 2;
            this.txt_Nombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Nombre.TextMarginBottom = 0;
            this.txt_Nombre.TextMarginLeft = 5;
            this.txt_Nombre.TextMarginTop = 0;
            this.txt_Nombre.TextPlaceholder = "Nombre Producto";
            this.txt_Nombre.UseSystemPasswordChar = false;
            this.txt_Nombre.WordWrap = true;
            this.txt_Nombre.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_Nombre_KeyPress);
            // 
            // txt_Codigo
            // 
            this.txt_Codigo.AcceptsReturn = false;
            this.txt_Codigo.AcceptsTab = false;
            this.txt_Codigo.AnimationSpeed = 200;
            this.txt_Codigo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Codigo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Codigo.BackColor = System.Drawing.Color.Transparent;
            this.txt_Codigo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Codigo.BackgroundImage")));
            this.txt_Codigo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.txt_Codigo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_Codigo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.txt_Codigo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Codigo.BorderRadius = 8;
            this.txt_Codigo.BorderThickness = 2;
            this.txt_Codigo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Codigo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Codigo.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.txt_Codigo.DefaultText = "";
            this.txt_Codigo.FillColor = System.Drawing.Color.White;
            this.txt_Codigo.ForeColor = System.Drawing.Color.Gray;
            this.txt_Codigo.HideSelection = true;
            this.txt_Codigo.IconLeft = null;
            this.txt_Codigo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Codigo.IconPadding = 10;
            this.txt_Codigo.IconRight = null;
            this.txt_Codigo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Codigo.Lines = new string[0];
            this.txt_Codigo.Location = new System.Drawing.Point(16, 71);
            this.txt_Codigo.MaxLength = 32767;
            this.txt_Codigo.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_Codigo.Modified = false;
            this.txt_Codigo.Multiline = false;
            this.txt_Codigo.Name = "txt_Codigo";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Codigo.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Codigo.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Codigo.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Gray;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Codigo.OnIdleState = stateProperties24;
            this.txt_Codigo.PasswordChar = '\0';
            this.txt_Codigo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Codigo.PlaceholderText = "ID Producto 000001.";
            this.txt_Codigo.ReadOnly = false;
            this.txt_Codigo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Codigo.SelectedText = "";
            this.txt_Codigo.SelectionLength = 0;
            this.txt_Codigo.SelectionStart = 0;
            this.txt_Codigo.ShortcutsEnabled = true;
            this.txt_Codigo.Size = new System.Drawing.Size(279, 38);
            this.txt_Codigo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_Codigo.TabIndex = 0;
            this.txt_Codigo.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txt_Codigo.TextMarginBottom = 0;
            this.txt_Codigo.TextMarginLeft = 5;
            this.txt_Codigo.TextMarginTop = 0;
            this.txt_Codigo.TextPlaceholder = "ID Producto 000001.";
            this.txt_Codigo.UseSystemPasswordChar = false;
            this.txt_Codigo.WordWrap = true;
            this.txt_Codigo.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_Codigo_KeyPress);
            this.txt_Codigo.Enter += new System.EventHandler(this.txt_Codigo_Enter);
            this.txt_Codigo.Validated += new System.EventHandler(this.txt_Codigo_Validated);
            // 
            // guna2Elipse1
            // 
            this.guna2Elipse1.BorderRadius = 8;
            this.guna2Elipse1.TargetControl = this;
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(232)))), ((int)(((byte)(191)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this.dataGridView1.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.dataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Sunken;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Orange;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(132)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridView1.ColumnHeadersHeight = 40;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(232)))), ((int)(((byte)(191)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.BackColor = System.Drawing.Color.Orange;
            this.dataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(226)))), ((int)(((byte)(173)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Orange;
            this.dataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(132)))), ((int)(((byte)(0)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.Name = null;
            this.dataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(237)))), ((int)(((byte)(204)))));
            this.dataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(237)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridView1.EnableHeadersVisualStyles = false;
            this.dataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(226)))), ((int)(((byte)(173)))));
            this.dataGridView1.HeaderBackColor = System.Drawing.Color.Orange;
            this.dataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridView1.Location = new System.Drawing.Point(12, 12);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            this.dataGridView1.RowHeadersVisible = false;
            this.dataGridView1.RowTemplate.Height = 40;
            this.dataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridView1.Size = new System.Drawing.Size(925, 626);
            this.dataGridView1.TabIndex = 0;
            this.dataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Orange;
            this.dataGridView1.CellEnter += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_CellEnter);
            // 
            // guna2Elipse2
            // 
            this.guna2Elipse2.BorderRadius = 8;
            this.guna2Elipse2.TargetControl = this.dataGridView1;
            // 
            // Ant
            // 
            this.Ant.AnimationHoverSpeed = 0.01F;
            this.Ant.AnimationSpeed = 0.01F;
            this.Ant.BackColor = System.Drawing.Color.Transparent;
            this.Ant.BaseColor = System.Drawing.Color.LightGray;
            this.Ant.BorderColor = System.Drawing.Color.Empty;
            this.Ant.BorderSize = 3;
            this.Ant.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Ant.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Ant.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Ant.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Ant.CheckedImage")));
            this.Ant.CheckedLineColor = System.Drawing.Color.Empty;
            this.Ant.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Ant.FocusedColor = System.Drawing.Color.Empty;
            this.Ant.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Ant.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Ant.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.Ant;
            this.Ant.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Ant.ImageSize = new System.Drawing.Size(40, 40);
            this.Ant.LineColor = System.Drawing.Color.Empty;
            this.Ant.Location = new System.Drawing.Point(12, 644);
            this.Ant.Name = "Ant";
            this.Ant.OnHoverBaseColor = System.Drawing.Color.White;
            this.Ant.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Ant.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ant.OnHoverImage = null;
            this.Ant.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Ant.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ant.Radius = 2;
            this.Ant.Size = new System.Drawing.Size(44, 44);
            this.Ant.TabIndex = 153;
            this.Ant.TextOffsetX = 10;
            this.Ant.Click += new System.EventHandler(this.Ant_Click);
            // 
            // Sig
            // 
            this.Sig.AnimationHoverSpeed = 0.01F;
            this.Sig.AnimationSpeed = 0.01F;
            this.Sig.BackColor = System.Drawing.Color.Transparent;
            this.Sig.BaseColor = System.Drawing.Color.LightGray;
            this.Sig.BorderColor = System.Drawing.Color.Empty;
            this.Sig.BorderSize = 3;
            this.Sig.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Sig.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Sig.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Sig.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Sig.CheckedImage")));
            this.Sig.CheckedLineColor = System.Drawing.Color.Empty;
            this.Sig.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Sig.FocusedColor = System.Drawing.Color.Empty;
            this.Sig.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Sig.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Sig.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.Sig;
            this.Sig.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Sig.ImageSize = new System.Drawing.Size(40, 40);
            this.Sig.LineColor = System.Drawing.Color.Empty;
            this.Sig.Location = new System.Drawing.Point(62, 644);
            this.Sig.Name = "Sig";
            this.Sig.OnHoverBaseColor = System.Drawing.Color.White;
            this.Sig.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Sig.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Sig.OnHoverImage = null;
            this.Sig.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Sig.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Sig.Radius = 2;
            this.Sig.Size = new System.Drawing.Size(44, 44);
            this.Sig.TabIndex = 152;
            this.Sig.TextOffsetX = 10;
            this.Sig.Click += new System.EventHandler(this.Sig_Click);
            // 
            // Pri
            // 
            this.Pri.AnimationHoverSpeed = 0.01F;
            this.Pri.AnimationSpeed = 0.01F;
            this.Pri.BackColor = System.Drawing.Color.Transparent;
            this.Pri.BaseColor = System.Drawing.Color.LightGray;
            this.Pri.BorderColor = System.Drawing.Color.Empty;
            this.Pri.BorderSize = 3;
            this.Pri.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Pri.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Pri.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Pri.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Pri.CheckedImage")));
            this.Pri.CheckedLineColor = System.Drawing.Color.Empty;
            this.Pri.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Pri.FocusedColor = System.Drawing.Color.Empty;
            this.Pri.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Pri.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Pri.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.arriba_01;
            this.Pri.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Pri.ImageSize = new System.Drawing.Size(40, 40);
            this.Pri.LineColor = System.Drawing.Color.Empty;
            this.Pri.Location = new System.Drawing.Point(837, 644);
            this.Pri.Name = "Pri";
            this.Pri.OnHoverBaseColor = System.Drawing.Color.White;
            this.Pri.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Pri.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Pri.OnHoverImage = null;
            this.Pri.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Pri.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Pri.Radius = 2;
            this.Pri.Size = new System.Drawing.Size(44, 44);
            this.Pri.TabIndex = 151;
            this.Pri.TextOffsetX = 10;
            this.Pri.Click += new System.EventHandler(this.Pri_Click);
            // 
            // Ult
            // 
            this.Ult.AnimationHoverSpeed = 0.01F;
            this.Ult.AnimationSpeed = 0.01F;
            this.Ult.BackColor = System.Drawing.Color.Transparent;
            this.Ult.BaseColor = System.Drawing.Color.LightGray;
            this.Ult.BorderColor = System.Drawing.Color.Empty;
            this.Ult.BorderSize = 3;
            this.Ult.CheckedBaseColor = System.Drawing.Color.Empty;
            this.Ult.CheckedBorderColor = System.Drawing.Color.Empty;
            this.Ult.CheckedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.Ult.CheckedImage = ((System.Drawing.Image)(resources.GetObject("Ult.CheckedImage")));
            this.Ult.CheckedLineColor = System.Drawing.Color.Empty;
            this.Ult.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Ult.FocusedColor = System.Drawing.Color.Empty;
            this.Ult.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.Ult.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(183)))), ((int)(((byte)(183)))));
            this.Ult.Image = global::SOFTWARE_INVENTARIO.Properties.Resources.abajo_01;
            this.Ult.ImageAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Ult.ImageSize = new System.Drawing.Size(40, 40);
            this.Ult.LineColor = System.Drawing.Color.Empty;
            this.Ult.Location = new System.Drawing.Point(887, 644);
            this.Ult.Name = "Ult";
            this.Ult.OnHoverBaseColor = System.Drawing.Color.White;
            this.Ult.OnHoverBorderColor = System.Drawing.Color.Empty;
            this.Ult.OnHoverForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ult.OnHoverImage = null;
            this.Ult.OnHoverLineColor = System.Drawing.Color.Empty;
            this.Ult.OnPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(176)))), ((int)(((byte)(59)))));
            this.Ult.Radius = 2;
            this.Ult.Size = new System.Drawing.Size(44, 44);
            this.Ult.TabIndex = 150;
            this.Ult.TextOffsetX = 10;
            this.Ult.Click += new System.EventHandler(this.Ult_Click);
            // 
            // Btn_Cerrar
            // 
            this.Btn_Cerrar.BackgroundImage = global::SOFTWARE_INVENTARIO.Properties.Resources.cerrar_Mesa_de_trabajo_1;
            this.Btn_Cerrar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.Btn_Cerrar.BorderColor = System.Drawing.Color.Transparent;
            this.Btn_Cerrar.BorderRadius = 6;
            this.Btn_Cerrar.CheckedState.Parent = this.Btn_Cerrar;
            this.Btn_Cerrar.CustomImages.Parent = this.Btn_Cerrar;
            this.Btn_Cerrar.FillColor = System.Drawing.Color.Transparent;
            this.Btn_Cerrar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Btn_Cerrar.ForeColor = System.Drawing.Color.White;
            this.Btn_Cerrar.HoverState.Parent = this.Btn_Cerrar;
            this.Btn_Cerrar.Location = new System.Drawing.Point(289, -43);
            this.Btn_Cerrar.Name = "Btn_Cerrar";
            this.Btn_Cerrar.PressedColor = System.Drawing.Color.White;
            this.Btn_Cerrar.ShadowDecoration.Parent = this.Btn_Cerrar;
            this.Btn_Cerrar.Size = new System.Drawing.Size(25, 25);
            this.Btn_Cerrar.TabIndex = 143;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.groupBox1);
            this.bunifuGroupBox1.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(943, 0);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(323, 700);
            this.bunifuGroupBox1.TabIndex = 1;
            this.bunifuGroupBox1.TabStop = false;
            // 
            // Txt_Buscar
            // 
            this.Txt_Buscar.AcceptsReturn = false;
            this.Txt_Buscar.AcceptsTab = false;
            this.Txt_Buscar.AnimationSpeed = 200;
            this.Txt_Buscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Txt_Buscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Txt_Buscar.BackColor = System.Drawing.Color.Transparent;
            this.Txt_Buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Txt_Buscar.BackgroundImage")));
            this.Txt_Buscar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.Txt_Buscar.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            this.Txt_Buscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Txt_Buscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            this.Txt_Buscar.BorderColorIdle = System.Drawing.Color.Silver;
            this.Txt_Buscar.BorderRadius = 8;
            this.Txt_Buscar.BorderThickness = 2;
            this.Txt_Buscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Txt_Buscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Txt_Buscar.DefaultFont = new System.Drawing.Font("Microsoft JhengHei UI", 11F, System.Drawing.FontStyle.Bold);
            this.Txt_Buscar.DefaultText = "";
            this.Txt_Buscar.FillColor = System.Drawing.Color.White;
            this.Txt_Buscar.ForeColor = System.Drawing.Color.Gray;
            this.Txt_Buscar.HideSelection = true;
            this.Txt_Buscar.IconLeft = null;
            this.Txt_Buscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Txt_Buscar.IconPadding = 10;
            this.Txt_Buscar.IconRight = null;
            this.Txt_Buscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Txt_Buscar.Lines = new string[0];
            this.Txt_Buscar.Location = new System.Drawing.Point(288, 650);
            this.Txt_Buscar.MaxLength = 32767;
            this.Txt_Buscar.MinimumSize = new System.Drawing.Size(100, 35);
            this.Txt_Buscar.Modified = false;
            this.Txt_Buscar.Multiline = false;
            this.Txt_Buscar.Name = "Txt_Buscar";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(159)))), ((int)(((byte)(28)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Txt_Buscar.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Txt_Buscar.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(173)))), ((int)(((byte)(5)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Txt_Buscar.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Gray;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Txt_Buscar.OnIdleState = stateProperties28;
            this.Txt_Buscar.PasswordChar = '\0';
            this.Txt_Buscar.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Txt_Buscar.PlaceholderText = "Buscar...";
            this.Txt_Buscar.ReadOnly = false;
            this.Txt_Buscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Txt_Buscar.SelectedText = "";
            this.Txt_Buscar.SelectionLength = 0;
            this.Txt_Buscar.SelectionStart = 0;
            this.Txt_Buscar.ShortcutsEnabled = true;
            this.Txt_Buscar.Size = new System.Drawing.Size(372, 38);
            this.Txt_Buscar.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Txt_Buscar.TabIndex = 159;
            this.Txt_Buscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.Txt_Buscar.TextMarginBottom = 0;
            this.Txt_Buscar.TextMarginLeft = 5;
            this.Txt_Buscar.TextMarginTop = 0;
            this.Txt_Buscar.TextPlaceholder = "Buscar...";
            this.Txt_Buscar.UseSystemPasswordChar = false;
            this.Txt_Buscar.WordWrap = true;
            this.Txt_Buscar.KeyUp += new System.Windows.Forms.KeyEventHandler(this.Txt_Buscar_KeyUp);
            // 
            // FormProducto
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1266, 700);
            this.Controls.Add(this.Txt_Buscar);
            this.Controls.Add(this.Ant);
            this.Controls.Add(this.Sig);
            this.Controls.Add(this.Pri);
            this.Controls.Add(this.Ult);
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.Btn_Cerrar);
            this.Controls.Add(this.bunifuGroupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormProducto";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormProducto";
            this.Load += new System.EventHandler(this.FormProducto_Load);
            this.groupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Guna.UI2.WinForms.Guna2Button Btn_Cerrar;
        private Bunifu.UI.WinForms.BunifuShadowPanel groupBox1;
        private Guna.UI2.WinForms.Guna2ComboBox cbx_Categoria;
        private Guna.UI2.WinForms.Guna2DateTimePicker txt_fecha;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Descripcion;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Cantidad;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Codigo;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse1;
        private Guna.UI2.WinForms.Guna2Button Btn_Salir;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridView1;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse2;
        private Guna.UI.WinForms.GunaAdvenceButton Pri;
        private Guna.UI.WinForms.GunaAdvenceButton Ult;
        private Guna.UI.WinForms.GunaAdvenceButton Ant;
        private Guna.UI.WinForms.GunaAdvenceButton Sig;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Actualizar;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Eliminar;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Guardar;
        private Guna.UI.WinForms.GunaAdvenceButton Btn_Nuevo;
        private Guna.UI2.WinForms.Guna2ShadowForm guna2ShadowForm1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.ToolTip toolTip1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Estado;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Txt_Buscar;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Nombre;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_Elemento;
    }
}